// Single source of truth for the Privacy Policy and Terms of Service.
//
// Two audiences read this text and both must see exactly the same words: the in-app screen
// (src/features/legal/LegalScreen.tsx) and the public page App Store Connect links to
// (public/legal.html, generated by `npm run build:legal`). Edit here, then run that script —
// never hand-edit public/legal.html, it is overwritten.

export interface LegalSection {
  heading: string;
  paragraphs: string[];
}

export interface LegalDocument {
  title: string;
  sections: LegalSection[];
}

export type LegalDocType = 'privacy' | 'terms';

// Bump this whenever the text below changes materially — it is the date users and App Review
// see. Deliberately a fixed string rather than a computed "current year": a policy that
// silently re-dates itself every January claims a review that never happened.
export const LEGAL_LAST_UPDATED = 'August 22, 2026';

export const LEGAL_CONTACT =
  "Questions about either document? Reach the developer through the app's App Store listing.";

export const LEGAL_DOCS: Record<LegalDocType, LegalDocument> = {
  privacy: {
    title: 'Privacy Policy',
    sections: [
      {
        heading: 'What we store',
        paragraphs: [
          'Pinpals stores the places, notes, and photos you create locally on your device. Account data — email address and display name — is managed through Firebase Authentication to sign you in; your display name is also used as noted below.',
        ],
      },
      {
        heading: 'What we share',
        paragraphs: [
          'We do not sell your data, and we do not share it with third parties except the infrastructure providers required to operate core features — Firebase (authentication, crash reporting, analytics) and Mapbox (maps, search, directions).',
        ],
      },
      {
        heading: 'Diagnostics',
        paragraphs: [
          'If the app crashes or hits an error, a report is sent to Firebase Crashlytics to help us fix it — this can include your display name, a Firebase-issued user ID, and basic device/app information, never your saved places or photos. Usage events are sent to Firebase Analytics, linked to that same user ID, to understand which features are actually used — never your saved places or photos.',
        ],
      },
      {
        heading: 'Deleting your data',
        paragraphs: [
          'You can delete your account and all associated data at any time from Profile > Delete Account. This permanently removes your places, memories, and profile from our systems and cannot be undone.',
        ],
      },
      {
        heading: 'Your responsibility',
        paragraphs: [
          'This app is provided for personal use "as is," without warranty of any kind. To the fullest extent permitted by law, the developer disclaims all liability for any loss or damage arising from your use of the app, including but not limited to data loss, service interruptions, or inaccuracies in map or location data. You are responsible for backing up any information you consider important.',
        ],
      },
      {
        heading: 'Changes',
        paragraphs: [
          'Continued use of the app constitutes acceptance of this policy, which may be updated from time to time. Material changes will be reflected here with an updated date above.',
        ],
      },
    ],
  },
  terms: {
    title: 'Terms of Service',
    sections: [
      {
        heading: 'Acceptable use',
        paragraphs: [
          'By using Pinpals, you agree to use the app for lawful, personal purposes only.',
        ],
      },
      {
        heading: 'Your content',
        paragraphs: [
          'You retain ownership of the photos, notes, and other content you create in the app. By using Pinpals, you grant the developer a limited license to store, process, and display that content back to you as needed to operate the service — we do not use your content for any other purpose.',
        ],
      },
      {
        heading: 'No warranty',
        paragraphs: [
          'The app is provided "as is" and "as available," without warranties of any kind, express or implied, including but not limited to fitness for a particular purpose, accuracy, or uninterrupted availability.',
        ],
      },
      {
        heading: 'Limitation of liability',
        paragraphs: [
          'To the maximum extent permitted by applicable law, the developer shall not be liable for any indirect, incidental, special, or consequential damages resulting from your use of, or inability to use, the app — including but not limited to data loss or reliance on map or directions data.',
        ],
      },
      {
        heading: 'Indemnification',
        paragraphs: [
          'You agree to indemnify and hold the developer harmless from any claims, damages, or expenses (including reasonable legal fees) arising from your use of the app, your violation of these terms, or your violation of any rights of a third party.',
        ],
      },
      {
        heading: 'Features in development',
        paragraphs: [
          'Features described as in development or "coming soon" are not guaranteed to ship on any particular timeline.',
        ],
      },
      {
        heading: 'Changes to the app or these terms',
        paragraphs: [
          'The developer reserves the right to modify or discontinue the app or these terms at any time without prior notice.',
        ],
      },
      {
        heading: 'Governing law',
        paragraphs: [
          'These terms are governed by the laws of the State of Israel, without regard to its conflict of law principles. Any dispute arising from these terms or your use of the app will be resolved in the competent courts of Israel.',
        ],
      },
      {
        heading: 'Severability',
        paragraphs: [
          'If any provision of these terms is found unenforceable, the remaining provisions will remain in full force and effect.',
        ],
      },
    ],
  },
};
