// Generates public/legal.html — the public Privacy Policy / Terms page that App Store Connect
// links to — from the same text the in-app screen renders (src/shared/legalContent.ts).
//
//   npm run build:legal
//
// public/legal.html is fully overwritten: edit the TS source, not the output.
//
//   npm run build:legal -- --check
//
// verifies the committed output is up to date instead of writing it — that is what CI runs, so
// a legal edit that never got regenerated fails the build rather than shipping a stale public
// page. TypeScript is loaded via Node's type stripping (--experimental-strip-types, a no-op
// flag on Node 23.6+ where stripping is on by default).

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const { LEGAL_CONTACT, LEGAL_DOCS, LEGAL_LAST_UPDATED } = await import(
  resolve(root, 'src/shared/legalContent.ts')
);

function escapeHtml(text) {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function renderSections(doc) {
  return doc.sections
    .map((section) => {
      const paragraphs = section.paragraphs
        .map((paragraph) => `    <p>${escapeHtml(paragraph)}</p>`)
        .join('\n');
      return `    <h2>${escapeHtml(section.heading)}</h2>\n${paragraphs}`;
    })
    .join('\n\n');
}

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>Pinpals — Privacy Policy &amp; Terms of Service</title>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="description" content="Privacy Policy and Terms of Service for the Pinpals app." />
<!-- Generated by scripts/build-legal.mjs from src/shared/legalContent.ts — do not edit by hand. -->
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link
  href="https://fonts.googleapis.com/css2?family=Nunito:wght@700;800&family=Inter:wght@400;500;600&display=swap"
  rel="stylesheet"
/>

<style>
  :root {
    --bg: #faf8f4;
    --surface: #ffffff;
    --surface-alt: #f0f5f2;
    --border: #e4ede8;
    --text: #1c2b22;
    --text-muted: #5a7a66;
    --text-faint: #7a9887;
    --brand: #4a7c59;
    --brand-dark: #2c5c3f;
    --accent: #e8834a;
    --focus-ring: #4a7c59;
  }

  @media (prefers-color-scheme: dark) {
    :root:not([data-theme='light']) {
      --bg: #16241c;
      --surface: #1e3328;
      --surface-alt: #223a2c;
      --border: #2e4436;
      --text: #eef4f0;
      --text-muted: #a0b8aa;
      --text-faint: #7a9887;
      --brand: #82b791;
      --brand-dark: #a3d0af;
      --accent: #f2a06b;
      --focus-ring: #82b791;
    }
  }

  :root[data-theme='dark'] {
    --bg: #16241c;
    --surface: #1e3328;
    --surface-alt: #223a2c;
    --border: #2e4436;
    --text: #eef4f0;
    --text-muted: #a0b8aa;
    --text-faint: #7a9887;
    --brand: #82b791;
    --brand-dark: #a3d0af;
    --accent: #f2a06b;
    --focus-ring: #82b791;
  }

  * {
    box-sizing: border-box;
  }

  body {
    margin: 0;
    background: var(--bg);
    color: var(--text);
    font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    font-size: 16px;
    line-height: 1.6;
    -webkit-font-smoothing: antialiased;
  }

  a {
    color: var(--brand);
  }

  a:focus-visible,
  button:focus-visible {
    outline: 2px solid var(--focus-ring);
    outline-offset: 2px;
  }

  .page {
    max-width: 680px;
    margin: 0 auto;
    padding: 56px 24px 96px;
  }

  header.brand {
    display: flex;
    align-items: center;
    gap: 14px;
    margin-bottom: 40px;
  }

  .pin-mark {
    width: 44px;
    height: 44px;
    flex: none;
    border-radius: 12px;
    background: var(--brand);
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .pin-mark svg {
    width: 24px;
    height: 24px;
  }

  .wordmark {
    font-family: 'Nunito', sans-serif;
    font-weight: 800;
    font-size: 22px;
    letter-spacing: 0.2px;
    color: var(--text);
  }

  .tagline {
    font-size: 13px;
    color: var(--text-muted);
    margin-top: 2px;
  }

  h1 {
    font-family: 'Nunito', sans-serif;
    font-weight: 800;
    font-size: 30px;
    line-height: 1.2;
    text-wrap: balance;
    margin: 0 0 6px;
    color: var(--text);
  }

  .updated {
    font-size: 13px;
    color: var(--text-faint);
    margin: 0 0 28px;
  }

  nav.switcher {
    display: inline-flex;
    padding: 4px;
    background: var(--surface-alt);
    border: 1px solid var(--border);
    border-radius: 999px;
    margin-bottom: 32px;
    gap: 2px;
  }

  nav.switcher button {
    appearance: none;
    border: none;
    background: transparent;
    font-family: 'Inter', sans-serif;
    font-weight: 600;
    font-size: 14px;
    color: var(--text-muted);
    padding: 9px 18px;
    border-radius: 999px;
    cursor: pointer;
    transition: background-color 0.18s ease, color 0.18s ease;
  }

  nav.switcher button[aria-selected='true'] {
    background: var(--brand);
    color: #ffffff;
  }

  @media (prefers-reduced-motion: reduce) {
    nav.switcher button {
      transition: none;
    }
  }

  section.doc {
    display: none;
  }

  section.doc.is-active {
    display: block;
  }

  section.doc p {
    margin: 0 0 18px;
    color: var(--text);
    max-width: 62ch;
  }

  section.doc p:last-child {
    margin-bottom: 0;
  }

  section.doc h2 {
    font-family: 'Nunito', sans-serif;
    font-weight: 700;
    font-size: 17px;
    margin: 30px 0 10px;
    color: var(--text);
  }

  section.doc h2:first-of-type {
    margin-top: 0;
  }

  .contact-card {
    margin-top: 36px;
    padding: 18px 20px;
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 14px;
  }

  .contact-card p {
    margin: 0;
    font-size: 14px;
    color: var(--text-muted);
  }

  footer {
    margin-top: 56px;
    padding-top: 20px;
    border-top: 1px solid var(--border);
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 12px;
    flex-wrap: wrap;
  }

  footer .foot-brand {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 13px;
    color: var(--text-faint);
  }

  footer .foot-brand svg {
    width: 14px;
    height: 14px;
    color: var(--brand);
  }

  footer .foot-links {
    display: flex;
    gap: 16px;
    font-size: 13px;
  }

  footer .foot-links a {
    color: var(--text-muted);
    text-decoration: none;
  }

  footer .foot-links a:hover {
    color: var(--brand);
  }
</style>
</head>
<body>

<div class="page">
  <header class="brand">
    <div class="pin-mark">
      <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path
          d="M12 2C7.86 2 4.5 5.36 4.5 9.5c0 5.5 6.5 12 7.5 12s7.5-6.5 7.5-12C19.5 5.36 16.14 2 12 2Z"
          fill="#ffffff"
        />
        <circle cx="12" cy="9.5" r="2.5" fill="#4a7c59" />
      </svg>
    </div>
    <div>
      <div class="wordmark">Pinpals</div>
      <div class="tagline">Places you've been. Moments worth keeping.</div>
    </div>
  </header>

  <h1 id="doc-title">${escapeHtml(LEGAL_DOCS.privacy.title)}</h1>
  <p class="updated">Last updated: ${escapeHtml(LEGAL_LAST_UPDATED)}</p>

  <nav class="switcher" aria-label="Legal document">
    <button type="button" data-doc="privacy" aria-selected="true">${escapeHtml(LEGAL_DOCS.privacy.title)}</button>
    <button type="button" data-doc="terms" aria-selected="false">${escapeHtml(LEGAL_DOCS.terms.title)}</button>
  </nav>

  <section class="doc is-active" id="privacy" aria-labelledby="doc-title">
${renderSections(LEGAL_DOCS.privacy)}
  </section>

  <section class="doc" id="terms" aria-labelledby="doc-title">
${renderSections(LEGAL_DOCS.terms)}
  </section>

  <div class="contact-card">
    <p>${escapeHtml(LEGAL_CONTACT)}</p>
  </div>

  <footer>
    <div class="foot-brand">
      <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path
          d="M12 2C7.86 2 4.5 5.36 4.5 9.5c0 5.5 6.5 12 7.5 12s7.5-6.5 7.5-12C19.5 5.36 16.14 2 12 2Z"
          fill="currentColor"
        />
      </svg>
      <span>Pinpals</span>
    </div>
    <div class="foot-links">
      <a href="#privacy" data-doc="privacy">${escapeHtml(LEGAL_DOCS.privacy.title)}</a>
      <a href="#terms" data-doc="terms">${escapeHtml(LEGAL_DOCS.terms.title)}</a>
    </div>
  </footer>
</div>

<script>
  (function () {
    var buttons = document.querySelectorAll('[data-doc]');
    var sections = {
      privacy: document.getElementById('privacy'),
      terms: document.getElementById('terms'),
    };
    var titles = ${JSON.stringify({ privacy: LEGAL_DOCS.privacy.title, terms: LEGAL_DOCS.terms.title })};
    var title = document.getElementById('doc-title');

    function show(doc) {
      Object.keys(sections).forEach(function (key) {
        sections[key].classList.toggle('is-active', key === doc);
      });
      document.querySelectorAll('nav.switcher button').forEach(function (btn) {
        btn.setAttribute('aria-selected', String(btn.getAttribute('data-doc') === doc));
      });
      title.textContent = titles[doc];
      if (history.replaceState) history.replaceState(null, '', '#' + doc);
    }

    buttons.forEach(function (el) {
      el.addEventListener('click', function (e) {
        if (el.tagName === 'A') e.preventDefault();
        show(el.getAttribute('data-doc'));
      });
    });

    var initial = window.location.hash.replace('#', '');
    if (initial === 'terms') show('terms');
  })();
</script>

</body>
</html>
`;

const outPath = resolve(root, 'public/legal.html');

if (process.argv.includes('--check')) {
  const current = await readFile(outPath, 'utf8').catch(() => null);
  if (current !== html) {
    console.error(
      'public/legal.html is out of date with src/shared/legalContent.ts.\n' +
        'Run `npm run build:legal` and commit the result.',
    );
    process.exit(1);
  }
  console.log('public/legal.html is up to date.');
} else {
  await writeFile(outPath, html, 'utf8');
  console.log(`Wrote ${outPath} (${html.length} bytes), last updated ${LEGAL_LAST_UPDATED}`);
}
